library(PoPS)
library(httr)
library(geojsonio)
library(protolite)
library(geojson)
library(rgdal)
library(raster)
library(jsonlite)
library(sp)
library(devtools)
library(doParallel)
library(foreach)
library(parallel)
library(aws.s3)
library(sf)
library(terra)
library(plumber)

pr <- plumber::plumb("schedule.R")
pr$run(host='0.0.0.0', port=8079)
