runtime: custom
env: flex
service: testing2

resources:
  cpu: 12
  memory_gb: 18
  disk_size_gb: 10
  
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 15
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.15
    
env_variables:
  GCS_AUTH_FILE: auth.json